---
- name: Install Lighthouse
  hosts: lighthouse
  roles: lighthouse-role
  notify: reload-nginx

- name: Install Clickhouse
- hosts: clickhouse
  become: true
  roles:
    - ansible-clickhouse
  notify: restart-ch

- name: Install Vector
  hosts: vector
  roles: vector-role
  notify: Start Vector service
