---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.64.59
      ansible_user: ansible

vector:
  hosts:
    vector-01:
      ansible_host: 51.250.64.59
      ansible_user: ansible

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.64.59
      ansible_user: ansible